shiftstack/shiftstack-ci

nuke-from-orbit.sh
Ideally, we never have any bugs in cluster delete.
However, even in this ideal scenario, we need
protection from a patch under review breaking cluster delete
and filling up our tenant with undeletable resources.
=> Add nuke-from-orbit script

run_ocp.sh
We check if there's an *available* floating IP we can use, we don't
want to be debugging duplicate IP address issues in the tenant.
Also make retrieving the newly floating IP more robust. Previously it
was getting a UUID instead of the IP against MOC.
=> Don't steal other's floating IP

hack/get-terraform.sh
The versions should match the ones vendored in the openshift-installer.
This is useful for example to test terraform templates.
Script based on the `hack/get-terraform.sh` one that was in openshift-installer at some point.
=> Add script to install terraform and openstack provider

run_ocp.sh
Use a smaller IP range for machineCIDR so that id doesn't include the
IP of the Upshift endpoints.
=> Reduce machineCIDR not to conflict with upshift endpoints

build_mco.sh
The DEST_IMAGE environment variable needs to be initialized after the
USERNAME one, otherwise the script tries to push images to
quay.io/origin-release:mco instead of the user's namespaced registry.
=> Fix issue where build_mco.sh omits the username when pushing

destroy_cluster.sh
This patch adds an option -i|--infra-id, that allows to specify a custom id for a cluster to destroy.
=> Allow to destroy cluster with custom infra id

run_ocp.sh
Otherwise it could pick floating IPs from different networks and fail
the installation with a cryptic neutron error indicating no more IP
addresses are available on the external network.
=> Check for available floating IP on the external network

build_mco.sh
Since https://github.com/openshift/machine-config-operator/pull/850 and
https://github.com/openshift/installer/pull/1875 the installer will
take a single image for the machine config operator.
=> Simplify building MCO image

build_mco.sh
The image building script in MCO was renamed and changed to only
rebuild image based on the git index, meaning we have to commit changes
to git in order to test something.
I find this new behavior rather annoying in a dev workflow and changed
our script to use podman build/push instead.
See https://github.com/openshift/machine-config-operator/pull/982 for
the upstream changes.
=> Fix build_mco.sh

clean-ci-resources.sh
This script deprovisions CI resources older than 5 hours.
=> Add script to cleanup orphaned CI resources

refresh_rhcos.sh
The default branch remains the 4.2 one. To use a different branch, call
the script with `--branch 4.3` for instance. The image will be suffixed
with the `-4.3` string in glance.
=> Make refresh_rhcos.sh script know openshift-installer branches

clean-ci-resources.sh
The CI-DNS VM is gone, there's no need anymore to curl to it on orphaned
cluster cleanup.
=> No longer curl to CI DNS on resource cleanup

clean-ci-resources.sh
The ci-dns floating IP has been deleted (woops).
=> Update project identifier

clean-ci-resources.sh, list-clusters
Add a new `list-clusters` command that can print a list of the active
clusters.
It is useful for listing stale resources:
```
openstack server list -f value -c ID -c Name | grep -vf <(./list-clusters -a)
```
=> List active clusters

cluster_config.sh.example, run_ocp.sh
This allows setting the BFV options in the cluster_config.sh for each
cloud.
=> Allow setting Boot from Volume

refresh_rhcos.sh
The image URL is used for determining whether decompression is needed.
Before this change, the image URL had the shasum as a query parameter,
thus disrupting the '*.gz' detection.
With this change, the sha256 argument is only added to the URL while
building the image cache filename.
=> Fix image URL

list-clusters
List UPI clusters as CI clusters, in both "active" and "stale" filters.
With this change, I should be able to:
* stop deleting resources from active UPI clusters
* start deleting resources from stale UPI clusters
=> Detect UPI clusters

refresh_rhcos.sh
Before this patch, an error in reaching the cluster was interpreted as a
grep failure.
By separating the call to openstack-cli from the call to grep, the
script now exits if openstack fails.
=> Fail if can't reach the cluster

clean-ci-resources.sh
For cleaning multiple stale clusters concurrently, run:
```
./clean-ci-resources.sh -c
```
=> Add an option for running clean concurrently

destroy_cluster.sh
`destroy_cluster.sh -fi xxx-xxx-xxx` comes handy for deleting image-registry data when installer-driven cluster deletion is stuck with undeletable resources.
=> destroy_cluster -f to remove the server group

refresh_rhcos.sh
Currently, the script fails if an image named `rhcos-4.x` is not present
in Glance.
With this change, the script proceeds with image upload in case
`openstack image show rhcos-4.x` fails.
=> Push the image if it is not present already

destroy_cluster.sh
By default, UPI networks are called `${INFRA_ID}-network`, whereas IPI
networks are called `${INFRA_ID}-openshift`.
=> Force-destroy the UPI network

destroy_cluster.sh
Keep `openstack` from lecturing you about the command's syntax in case `$PORT` is empty or unset.
=> Only remove router port if port exists

clean-ci-resources.sh
There's a bunch of old containers in the CI tenant, some empty, some
having ~500MB of files.
Let's delete the ones with no associated active cluster. I'm
intentionally checking for the router rather than for the network
because of name consistency between UPI and IPI.
=> Delete leftover containers from CI tenant

stale
List resources that were last updated more than 5 hours ago.
Usage:
```shell
./stale port
./stale -nu floating ip
```
* `-u`  Also prints the timestamp of the last update
* `-n`  Also prints the resource name
Implemented for:
* server
* port
* network
* network trunk
* subnet
* floating ip
* security group
=> List stale resources

docs/README.adoc
ref: https://github.com/openshift/release/pull/10482
=> Update docs: 4.6 periodics now run on Vexxhost

README.md, cluster_config.sh.moc.example, cluster_config.sh.psi.example
Now our example contains defaults for MOC platform. Since most of the time we deploy on PSI, it makes sense to add another example with PSI defaults.
=> Create a cluster config example for PSI

run_ocp.sh
This parameter is enabled by default anyway, so there is no reason to set it in the install config.
https://github.com/openshift/installer/blob/master/data/data/install.openshift.io_installconfigs.yaml#L46
=> Do not add "hyperthreading: Enabled" for machine sets

populate_mirror.sh
I use that script to mirror the OCP images into a local registry at
home.
This script can be useful for anyone who wants to do disconnected
installations in order to:
- deploy OCP without Internet access
- save bandwidth by pre-fetching container images frequently and store
them in a registry instead of pulling them at each deployment.
Requirements:
- a functional container image registry (e.g. docker-registry)
- Internet access
- 8 GB available for the registry (subject to change)
- oc binary installed
- auth file generated with valid credentials
Usage:
./populate_mirror.sh -r myregistry.io
Required option: -r/--registry
Available options (with sane defaults):
-h/--help to print help
-d/--debug to enable debug
--arch to override default x86_64 arch
--auth to specify the auth.json file …
=> Add a script for Mirroring the OCP image repository

.gitignore, destroy_cluster.sh, run_ocp.sh
The cluster artifacts are now all saved in a `clusters` directory to
stop polluting the root of the repository.
Also delete existing artifact directory when re-running the install script.
=> Save cluster artifacts in its own directory

builders/build_capo.sh
This will help to build openshift/capo without complication.
You just need a valid auth file and that's it.
If you want to specify a directory for CAPO, use $CAPO_DIR and it won't
clone it.
Also it adds some validation at the end to make sure that the release
image is usable for an actual deployment.
Signed-off-by: Emilien Macchi <emilien@redhat.com>
=> Make builders/build_capo.sh working out of the box

builders/README.md, builders/build_capo.sh, builders/build_mco.sh, builders/config.json.example
registry.svc.ci.openshift.org has been deprecated, and we have to start using registry.ci.openshift.org
Allso we need to update the documentation on how to get credentials for the new registry.
=> Start using new registry for image builders

README.md
In the readme, "Pre-Requisits" -> "Prerequisites"
=> Typo fix in the readme

refresh_rhcos.sh
With this patch, a failed upload no longer prevents further tries.
=> Refresh: Use image id on upload

server.sh
Explicitly set the DNS on the subnet, so that the script is more
resilient WRT the cloud's configuration.
=> server: Set subnet DNS

populate_mirror.sh
Include the product registry URL in the PRODUCT_REPO variable,
so an user can override quay.io with another source.
e.g.:
```
./populate_mirror.sh -p registry.ci.openshift.org/test-repo (...)
```
=> populate_mirror.sh: allow to override product registry

populate_mirror.sh
In some cases, if we want to use "latest" tag, we don't want the
architecture in the tag name.
Let's remove OCP_RELEASE and ARCHITECTURE, to have one single
parameter: TAG (-t / --tag).
Also fixing --debug.
Also making it work for a custom local registry.
=> populate_mirror: improvements to make it work with CI

clean-ci-resources.sh
instead of relying on an ad-hoc security group.
With this, pruning security groups can be done more easily, as fewer
exceptions have to be made to the "expiration date" rule.
=> Use the default SG to identify cloud

run_ocp.sh
This prevents stealing FIP from someone else who might have added it to
a DNS.
=> Reuse your own floating IPs

clean-ci-resources.sh, report.sh
Remove Slack as a reporting tool.
Report instead in the Open Metrics format, for Prometheus to parse.
Further reporting and alerting can be built on Prometheus.
a prerequisite for shiftstack-bot automation.
=> report: Slack out, Prometheus in

.gitignore, Makefile, bot/clean-ci-resources.yaml, bot/inventory.yaml, bot/openstack-credentials.sh, bot/templates/Caddyfile.j2, bot/templates/clean-ci-resources.service.j2, bot/templates/clean-ci-resources.timer.j2, bot/templates/clouds.yaml.j2, bot/templates/secure.yaml.j2, server.sh
* Creates application credentials
* Creates a server in OpenStack and uploads the application credentials
to it
* Installs systemd services and timers to run the cleanup
* Exposes the cleanup results to localhost:9097 in the Open Metrics
format
=> clean-ci-credentials: shiftstack-bot automation

clean-ci-resources.sh
Cleanup the cleanup script.
Remove the concurrency option.
Optionally output the JSON result to a given file. Leave all output
untouched from the cleanup commands.
=> Clean cleanup

clean-ci-resources.sh, list-clusters
This commit includes the clean up of leftovers in
the Kuryr Cloud. Also, it makes sure to keep retriving
the clusterID only from the Nodes Network.
=> Include clean up of Kuryr Cloud

clean-ci-resources.sh
We redeployed the cloud today, so we need to update the UUID in
clean-ci-resources.sh script.
=> Update UUID for vh-mecha security group

stale
It avoids messages like:
```
Failed to delete group with name or ID '1e7008c1-10f4-4d09-9d6e-d3de70b62eb6': ConflictException: 409: Client Error for url: https://network.rdo.mtl2.vexxhost.net/v2.0/security-groups/1e7008c1-10f4-4d09-9d6e-d3de70b62eb6, Insufficient rights for removing default security group.
```
=> Don't clean default SGs

borderline.sh
This script can be used in CI to report if some of our resources are
closed to reach the maximum quota limit.
By default, it reports if a resource has less than 15% free.
It relies on "openstack limits show --absolute" and it was tested
against multiple clouds: PSI, VEXXHOST managed, mecha.
Example of output:
```
./borderline.sh --min-percentage 50
WARNING: Only 40% of Cores are available
WARNING: Only 22% of RAM are available
```
=> Add a script to report borderline quota usage

clean-ci-resources.sh
If some staled volumes are marked as 'reserved', they can't be removed.
They first need to me set as 'error' and then later they can be removed.
This patch will add a check if the resource is a volume and is reserved,
we mark it as error, so later it can be removed.
=> clean-ci-resources: mark undeletable volumes as 'error'

borderline.sh
* Align results when quotas are unlimited
* Don't show it twice when a quota is low
=> borderline: small visual improvements

clean-ci-resources.sh, stale
This was tested against `mecha` and it cleans staled keypairs.
=> clean-ci: add keypair to resources to clean

borderline.sh
When a limit is set to 0, it just means there is no quota for that
resource, and we can't create any; so we can skip it and go to the next
resource.
It'll avoid this type of error:
```
./borderline.sh: line 48: ((: percentage_value=0*100/0: division by 0 (error token is "0")
```
=> borderline: fix when limit is set to 0

borderline.sh
If all resources are exhausted, we want to show a CRITICAL error
message.
=> borderline: add CRITICAL message is no more resource

clean-ci-resources.sh
We are splitting into 2 projects, for each AZ, so Security Groups
changed.
=> clean-ci-resources.sh: update SGs for mecha projects

run_ocp.sh
The regex was too loose and might return the wrong ingress port in the
event you're deploying a cluster which name is the beginning of an
existing cluster's name.
=> Be more specific when discovering ingress port

clean-ci-resources.sh
This is getting annoying as the marker changes when we re-deploy
vh-mecha. Instead, force the script to be called with the
`--delete-everything-older-than-5-hours` option.
=> Stop requiring IDs of CI tenants in clean-ci-resources.sh

borderline.sh
Prior to this patch, borderline.sh returned 1 when low quota was
detected, making it difficult to distinguish the outcome from a crash.
With this patch, borderline.sh returns with code 11 when low quota is
detected.
=> borderline.sh: Signal low quota

server.sh
* Add a new argument (-u) which when set can be used to test
connectivity from the created instance (a ping).
e.g. -u centos when using a CentOS image.
* Add a new argument (-t) which can be set to disable interactions.
Useful when the script is run by CI tools.
* Add a new argument (-d) which can be set to enable debug.
Useful to figure out when an OpenStack command fails, to know why.
* Now the script will create a volume in Cinder and test boot from
volume.
* The script creates a loadbalancer and its resources, to reach the
instance via SSH; so we test the Octavia + OVN integration
=> Adding Cinder & Octavia to server.sh

server.sh
When creating a server and assigning a floating IP to the port, it can
take a few seconds before we can actually SSH.
Let's have a timeout of 30s.
Host verification can be disabled in the context of CI, this makes it
easy to use in ephemeral environments.
=> server: few changes for SSH

server.sh
* Use --cascade --wait to destroy LB resources, it's faster and also
more reliable as it follows an internal workflow in Octavia. It
avoids errors like:
```
Load Balancer b871e768-71b2-4b71-98b5-72cb2b5a231e is immutable and cannot be updated. (HTTP 409)
```
When the steps are run manually (like before).
* Don't remove the subnet, deleting the network will remove the subnet.
This saves a little bit of time and code.
* Fix a shellcheck issue
=> server: faster resource destroy

server.sh
It might take a bit of time so the VM is fully started and SSH being
available.
Adding a sleep will reduce the change to hit connection errors.
=> server: add a sleep before SSH'ing the VM

Containerfile, hack/dnf_safe
Fedora repos are not reliable, and very often we have issues when
building the images, where the repo is not available, under heavy use
and therefore can't serve the packages that we need.
This is problematic as it's causing some of our CI jobs to fail, and
creating a lot of noise.
To address this issue, we propose to implement an hack to safely run
DNF with retries (up to 10 retries when a failure is hit, with 5s of
break between attempts).
This patch also adds python3-openstackclient & python3-octaviaclient
& jq which are needed by our CI job running shiftstack-ci specific
jobs.
=> Containerfile: hack to have more reliable builds

server.sh
To avoid race condition when we create a LB resource that depends on
a parent resource, we can use `--wait` argument so the resource is
created for sure when the commands finishes, before we go to the next
command that creates a child resource.
That will help us to avoid things like:
```
Load Balancer 4b87150b-e5a9-4cb7-b34f-e3196a9f5bdc is immutable and cannot be updated. (HTTP 409) (Request-ID: req-f04bcbab-b9eb-40ec-b7ea-eb716ec91ad9)
```
=> server: use --wait when creating LB resources

run_ocp.sh
When multiple FIPs matched the search criteria, the script would take
all of then and insert them in the install-config.yaml as following:
platform:
openstack:
[...]
lbFloatingIP:     128.31.26.47
128.31.26.253
This later caused the installer to fail with:
FATAL failed to fetch Metadata: failed to load asset "Install Config": failed to unmarshal install-config.yaml: error converting YAML to JSON: yaml: line 36: could not find expected ':'
This patch selects the first FIP matching the search criteria.
=> Fix getting FIP when multiple matches

clean-ci-resources.sh
Why did we not include load balancers in the cleanup script?
=> Clean up load balancers

run_ocp.sh
The awk command was wrong and resulted in no IP address being printed
out.
This commit copies the command we use to retrieve the API FIP if it
exists.
=> Fix command to get existing ingress FIP

stale.sh
This is created in MOC, where apparently Sahara is available therefore
this network can't be removed.
=> state: skip "sahara-access" network

clean-ci-resources.sh
We should delete LB before deleting subnets as it the former had
a dependency on the latter.
Since no resource have dependency on LBs, we can delete them first.
=> Cleanup LB first

run_ocp.sh
It looks like it has never been a valid attribute in
install-config.yaml. Recent change in OCP 4.10 now validate the
install-config.yaml and errors out on unknown attributes. We should then
drop it.
=> Remove clusterID from install-config.yaml

stale.sh
NFV networks will be named intel-sriov, intel-dpdk, mellanox-sriov and
mellanox-dpdk. Let's ignore them when clearing staled networks.
=> stale: exclude NFV networks

destroy_cluster.sh
The CONFIG environment variable as sourced in destroy_cluster.sh uses a
relative path prefix of ./ which causes issues when you specify a full
path to the script. Changing to not use relative path results in the
execution matching that of run_ocp.sh.
Co-Authored-By: Emma Foley <efoley@redhat.com>
Signed-off-by: Leif Madsen <lmadsen@redhat.com>
=> destroy_cluster.sh relative path in CONFIG

destroy_cluster.sh
This script is run in our CI and the job currently timeouts if
`openshift-install destroy` never manage to finish (it's the case when a
resource is not destroyed). So let's run the destroy command during 15
minutes and if it didn't finish on time, report it in the logs but move
on.
Later, we have code that will force the deletion of these ressources.
=> destroy_cluster: run cluster destroy with a timeout

clean-ci-resources.sh
Add the `ACTIVE` state in the case statement. If a LB is ACTIVE or in
ERROR, it can be cleaned up.
=> clean-ci-resources: clean LB resources in ACTIVE state

bump-periodics.sh
* The periodics of the branch under development should target the "ci"
stream for getting signal early;
* The periodics of the released branches should target the "nightly"
stream to avoid noise.
This is the logic I applied to https://github.com/openshift/release/pull/29785. The 4.12 nightly images are not even available yet.
=> bump-periodics: Set tip stream to "ci"

clean-ci-resources.sh
Make sure that the cleanup script doesn't remove it.
=> Move shiftstack-metrics to Vexxhost

stale.sh
This commit makes sure the clean-up script does not clean the ipv6 network and subnet used by the CI in the ipv6 job.
=> Exclude IPv6 Network and Subnet

bump-periodics.sh
We want the jobs to use the newly introduced periodic type to spread them better.
=> bump-periodics.sh: Prefer minimum_interval over interval

metrics.sh
They work differently. The current implementation just errors.
=> metrics: Remove volumes

metrics.sh
New metric openstack_server: OpenStack servers by status. Useful to track ERRORed instances.
=> metrics: Expose server status

server.sh
Start dumping the server console when a liveliness check fails. This should give us a little more context to work with when debugging things.
While we're here, we also increase the timeout in case it's the obvious issue of slow infra. One can hope, right?
=> Dump console on liveliness check failure

connectivity-test-cloud-init.yaml, server.sh
The previous SSH test was prone to sporadic failures with a failure rate above 10% for the amphora driver in vh-mecha-central. The HTTP test has been reliable so far in testing.
The liveliness periodic invokes server.sh with `-u centos`, which both supplied the username to use when logging in via SSH and enabled the test. We no longer require a login username for the test so we add a new option `-l` which enables the test without taking an option. We retain the `-u` option for compatibility with the periodic. It can be removed after we have updated the periodic.
=> Make the liveliness periodic more robust

server.sh
This will allow us to remove keypair generation from the periodic, as it's no longer required.
Also remove some curl noise from the logs.
=> Make -k <keypair> optional

stale.sh
Now that we have subnets for externallb jobs, we need to relax the matching otherwise it fails to cleanup leaked resources by those jobs.
=> Relax regex for external subnets

clean-ci-resources.sh
The proxy and az jobs create resources that may not be cleaned up upon job completion.
One such example was seen in
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-shiftstack-shiftstack-ci-main-periodic-4.13-e2e-openstack-az/1632828398344605696 where the leftover port on the proxy machine subnet caused the cleanup script to fail.
=> Remove potential stale ports before cleaning subnet

team_ssh_keys.sh
This script will generate a temporary file with all the ssh keys of the
approvers of a given group in the OWNERS_ALIASES file of a given project.
The script will return the path of the temporary file.
The script will return 1 if the script fails to curl the OWNER_ALIASES file
or if the yq command is not found.
=> Add team_ssh_keys.sh

team_ssh_keys.sh
This is a neat script, @EmilienM!
Here I propose to change the API and let the caller decide whether to redirect the output to a file.
In the case of an interactive invocation, the behaviour of the current version could be emulated with:
```bash
./team_ssh_keys.sh > $(mktemp | tee /dev/tty)
```
=> team_ssh_keys: Output to stdout

team_ssh_keys.sh
As Github allows including more than a key, switch to a style of commenting that is clear when there is more than one key per person.
=> team_ssh_keys: Comment keys accounting for multiple entries

clean-ci-resources.sh, list-clusters.sh, stale.sh
Also rename the flag `--delete-everything-older-than-5-hours` to `--no-dry-run`
=> Set timeout for cleanup at 7h

server.sh
So we can monitor mecha-az0 too at some point.
=> server.sh: add AZ support

destroy_cluster.sh
The worker server groups don't get deleted, which can cause deployment failues due to insufficient quota in OpenStack
=> Clean up INFRA_ID-worker server groups

cluster_config.sh.example, run_ocp.sh
Make the networkType configurable depending on the OCP version to use.
For now, default to OpenShiftSDN.
OpenShiftSDN was deprecated in OCP 4.15 and will be removed in OCP 4.16
=> Expose the networkType config in run_ocp
