shiftstack/shiftstack-ci

- .gitignore
- README.md
- build_ocp.sh
- cluster_config.sh
- destroy_cluster.sh
- run_ocp.sh
port from ocp doit
+build
+run
+delete
++how to use stuff in readme
> Added build, run, delelete scripts. Updated readme to match.

- destroy_cluster.sh
Few improvements to the destroy_cluster script.
> Destroy cluster

- refresh_rhcos.sh
Add script to refresh RHCOS image in remote cloud.
> Refresh rhcos

- build_mco.sh
Lets you push to a custom tag, so that you can keep multiple versions built in your own repo
> lets you push to custom tags

- get-rhcos-image.sh
Script allows you to search and download rhcos images to local machine
> Adding script to download rhcos images

- refresh_rhcos.sh
So we don't have to update the script for every new release.
> Make refresh_rhcos.sh forward compatible

- refresh_rhcos.sh
* Added a couple quotes
* Uses the Installer image cache (goes both ways: Installer will reuse the image cached by this tool)
> Refresh to use the Installer cache

- clean-ci-resources.sh
Just a proposal. I am running this, but not everyone might like it.
> RFE: Delete clusters concurrently

- clean-ci-resources.sh
A project identifier security group was added to Vexxhost.
> Allow operating on Vexxhost

- pull-artifacts
This is the script I use for fetching a CI job's artifacts.
> Pull-artifacts

- cluster_config.sh.example
https://tools.ietf.org/html/rfc2606
> Make example BASE_DOMAIN rfc2606 compliant

- server.sh
and expose it using a floating IP.
A convenience script for quickly creating a temporary server
* in its own network
* with SSH & ping ingress rules.
> server.sh: Create a server in its own network

- clean-ci-resources.sh
for consistency with the other resources in the same script.
> clean: Delete containers verbosely

- server.sh
a prerequisite for shiftstack-bot automation.
> server: shorten FIP description

- report.sh
a prerequisite for shiftstack-bot automation.
> report: Log on Swift

- Makefile
- clean-ci-resources.sh
This is mainly to test the Prow integration; more scripts may be added
to the check later.
> Add a shellcheck job

- clean-ci-resources.sh
Clean security groups that have been staled in the cloud.
> clean/ci: add Security Groups

- borderline.sh
`openstack limits show` is less reliable for the network resources, so
we switch to quota list, which reports good metrics for both compute
& network.
> borderline: switch to `openstack quota list --detail`

- clean-ci-resources.sh
A follow-up on https://github.com/shiftstack/shiftstack-ci/pull/156
> cleanup: Only delete ERRORed load balancers

- clean-ci-resources.sh
> cleanup: Fix LB deletion

- clean-ci-resources.sh
- stale.sh
This now remove stale servers, routers, subnets, and networks. Useful
for when a BYON leaks resources.
Implements [OSASINFRA-2729](https://issues.redhat.com/browse/OSASINFRA-2729)
> Clean more resources with the CI cleanup script

- refresh_rhcos.sh
The rhcos.json path and content changed in release-4.10, we need to
update the script to take that into account.
> Refresh-rhcos.sh: support releases >= 4.10

- metrics.sh
> metrics.sh: Add volume quota

- clean-ci-resources.sh
Context:
https://redhat-internal.slack.com/archives/C0201AD6NCV/p1685372604658259?thread_ts=1685372381.952679&cid=C0201AD6NCV
> clean: try to force-detach a volume if it's still attached
